// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosXyd0oyKulPXXX2-AWuFAcmlZGJehNE',
    appId: '1:985224061343:web:386b1812e6a83df4539daa',
    messagingSenderId: '985224061343',
    projectId: 'romanticdeveloper-bf7f5',
    authDomain: 'romanticdeveloper-bf7f5.firebaseapp.com',
    storageBucket: 'romanticdeveloper-bf7f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFd7McVS0kFaSS5BVbDYO1qtgwG8K461U',
    appId: '1:985224061343:android:6df3cb4413afb48c539daa',
    messagingSenderId: '985224061343',
    projectId: 'romanticdeveloper-bf7f5',
    storageBucket: 'romanticdeveloper-bf7f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtMOKHRSBT0eOkGYxIpgdFGlIDinWQGU',
    appId: '1:985224061343:ios:4dd71a1502c92947539daa',
    messagingSenderId: '985224061343',
    projectId: 'romanticdeveloper-bf7f5',
    storageBucket: 'romanticdeveloper-bf7f5.appspot.com',
    iosClientId: '985224061343-lo0ontsh84qb8gio6kko2drpiobbhu30.apps.googleusercontent.com',
    iosBundleId: 'com.example.romanticdeveloper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtMOKHRSBT0eOkGYxIpgdFGlIDinWQGU',
    appId: '1:985224061343:ios:4dd71a1502c92947539daa',
    messagingSenderId: '985224061343',
    projectId: 'romanticdeveloper-bf7f5',
    storageBucket: 'romanticdeveloper-bf7f5.appspot.com',
    iosClientId: '985224061343-lo0ontsh84qb8gio6kko2drpiobbhu30.apps.googleusercontent.com',
    iosBundleId: 'com.example.romanticdeveloper',
  );
}
